const fonts = [
    "Arial",
    "Verdana",
    "Times New Roman",
    "Georgia",
    "Courier New",
    "Tahoma",
    "Trebuchet MS",
    "Comic Sans MS",
    "Impact",
    "Lucida Console",
    "Lucida Sans Unicode",
    "Palatino Linotype",
    "Book Antiqua",
    "Garamond",
    "Calibri",
    "Candara",
    "Century Gothic",
    "Franklin Gothic Medium",
    "Futura",
    "Gill Sans MT",
    "Helvetica Neue",
    "Myriad Pro",
    "Optima",
    "Rockwell",
    "Segoe UI"
];